server:
  port: 9004
  
spring:
  application:
    name: API-GATEWAY
  
  cloud:
    gateway:
      routes:
      # - id: LEAD-SERVICE
      #   uri: http://localhost:9001
      #   predicates:
      #   - Path=/leadService/**
      # - id: CORPSEED-SECURITY
      #   uri: http://localhost:9990
      #   predicates:
      #   - Path=/securityService/**
        - id: AzureDeploymentTesting-1
        uri: http://localhost:8080
        predicates:
        - Path=/test
        
        
          
        

# eureka:
#   instance:
#     ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka 
  
